// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Container: typeof import('./src/components/Container.vue')['default']
    copy: typeof import('./src/components/Task/TaskWord copy.vue')['default']
    Detail: typeof import('./src/components/Detail.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Hamburger: typeof import('./src/components/Hamburger.vue')['default']
    HomeLearn: typeof import('./src/components/Home/HomeLearn.vue')['default']
    HomeWelcome: typeof import('./src/components/Home/HomeWelcome.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskPrompt: typeof import('./src/components/Task/TaskPrompt.vue')['default']
    TaskWord: typeof import('./src/components/Task/TaskWord.vue')['default']
    Text: typeof import('./src/components/Text.vue')['default']
  }
}
